stages:
  1_get_biomaRt_GeneAttribute_files:
    cmd: Rscript 1_get_biomaRt_GeneAttribute_files.R
    deps:
    - 1_get_biomaRt_GeneAttribute_files.R
    - species.txt
    outs:
    - 1_BioMart_gene_attributes/
  2_get_biomaRt_GO_files:
    cmd: Rscript 2_get_biomaRt_GO_files.R
    deps:
    - 2_get_biomaRt_GO_files.R
    - species.txt
    outs:
    - 2_BioMart_GO_attributes
  3_processAllPCfile_with-scaffolds:
    cmd: perl 3_processAllPCfile_with-scaffolds.pl
    deps:
    - 1_BioMart_gene_attributes
    - 2_BioMart_GO_attributes
    - 3_processAllPCfile_with-scaffolds.pl
    outs:
    - 3_Prepare_final_gene_files_all-scaffolds
